# Generated by Django 2.2.4 on 2019-08-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
